export const GET_USER_DATA_START = 'GET_USER_DATA_START';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_RECOMMENDED_POEMS_START = 'FETCH_RECOMMENDED_POEMS_START';
export const FETCH_RECOMMENDED_POEMS_SUCCESS = 'FETCH_RECOMMENDED_POEMS_SUCCESS';
export const FETCH_RECOMMENDED_POEMS_FAIL = 'FETCH_RECOMMENDED_POEMS_FAIL';

export const FETCH_POEM_PREVIEW_START = 'FETCH_POEM_PREVIEW_START';
export const FETCH_POEM_PREVIEW_SUCCESS = 'FETCH_POEM_PREVIEW_SUCCESS';
export const FETCH_POEM_PREVIEW_FAIL = 'FETCH_POEM_PREVIEW_FAIL';

export const FETCH_POEM_START = 'FETCH_POEM_START';
export const FETCH_POEM_SUCCESS = 'FETCH_POEM_SUCCESS';
export const FETCH_POEM_FAIL = 'FETCH_POEM_FAIL';

export const FETCH_AUTHORS_START = 'FETCH_AUTHORS_START';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAIL = 'FETCH_AUTHORS_FAIL';

export const FETCH_OVERVIEW_START = 'FETCH_OVERVIEW_START';
export const FETCH_OVERVIEW_SUCCESS = 'FETCH_OVERVIEW_SUCCESS';
export const FETCH_OVERVIEW_FAIL = 'FETCH_OVERVIEW_FAIL';

export const CREATE_NEW_POEM_START = 'CREATE_NEW_POEM_START';
export const CREATE_NEW_POEM_SUCCESS = 'CREATE_NEW_POEM_SUCCESS';
export const CREATE_NEW_POEM_FAIL = 'CREATE_NEW_POEM_FAIL';

export const ADD_NEW_AUTHOR_START = 'ADD_NEW_AUTHOR_START';
export const ADD_NEW_AUTHOR_SUCCESS = 'ADD_NEW_AUTHOR_SUCCESS';
export const ADD_NEW_AUTHOR_FAILURE = 'ADD_NEW_AUTHOR_FAILURE';

export const ADD_NEW_CATEGORY_START = 'ADD_NEW_CATEGORY_START';
export const ADD_NEW_CATEGORY_SUCCESS = 'ADD_NEW_CATEGORY_SUCCESS';
export const ADD_NEW_CATEGORY_FAILURE = 'ADD_NEW_CATEGORY_FAILURE';

export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_CANCEL = 'AUTH_CANCEL';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const REG_START = 'REG_START';
export const REG_SUCCESS = 'REG_SUCCESS';
export const REG_FAILURE = 'REG_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';